### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by XoAlone** [jnarezo/canvas-discord-bot#4]
**Hello**, I have an issue. When I do -remind <course> <assignment>, it says "No matching assignment. Please check your search criteria.". Why does it say that?

**Comment by jnarezo** [comment]
This error occurs when the bot found the course you were searching for, but none of its upcoming assignments 
matched the assignment's name you passed in the command.

All arguments are automatically separated by spaces, so please check if you need double-quotes which are required to encapsulate multiple words.
(i.e. `-remind 6h CSE30 "Programming Assignment 1"`, where the bot tries to find an assignment that has *Programming Assignment 1*)

If the arguments were correct, the bot only searches for **upcoming assignments** as specified by Canvas which are assignments assigned to you, with a due-date.

If the problems above don't seem to apply, it would be great if you could describe the command you used and the assignment and I'll look into the problem a bit further! 👍

**Comment by XoAlone** [comment]
So I tried what you did and it worked, but now it's giving me this error:
![image](https://user-images.githubusercontent.com/70545644/93598726-1b2e2200-f98b-11ea-93fe-090823a46af5.png)

**Comment by XoAlone** [comment]
Nevermind, I fixed it.

**Comment by XoAlone** [comment]
I have another issue, when I do ;subscribe <course>, it gives "2020-09-18T15:28:54.056Z [warn]: Unable to fetch courses from subscribe:  course is not defined" error.

**Comment by jnarezo** [comment]
`subscribe` requires a course name, which is the course you will get updates for. Currently the command checks for new updates every 6 hours for each subscribed course at once, but you must manually subscribe to each course.

Did you try something like `;subscribe French`?

**Comment by XoAlone** [comment]
Yes I have tried **;subscribe French** but it did not work.
![image](https://user-images.githubusercontent.com/70545644/93657973-40f80d00-fa05-11ea-8236-265441114c3c.png)

**Comment by jnarezo** [comment]
Thank you for letting me know about this issue.

The `subscribe` command is sort of experimental, but the issue should be corrected now. 👍

**Comment by XoAlone** [comment]
It works now, thanks a lot.
