### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Nooboizee** [jnarezo/canvas-discord-bot#8]
Hi! 
I recently discovered your bot and wanted to set it up before the school year started. (I am self hosting it)
When I tried the commands, none of them work. I gave the bot the highest role with admin, and made sure the bot could read and send messages in all channels. Everything in Config is set up correctly, and I did not mess with any other files.

Could you help me fix this problem? Thank you.

**Comment by jnarezo** [comment]
Yeah sure! Can you describe what exactly is going wrong or any error messages? It sounds like its not responding right?

**Comment by Nooboizee** [comment]
The bot is not sending any output to my commands. It is not sending anything at all. I tried using multiple different bots, on different servers. I don't know if it's something with how I set up the bots or if I configured something wrong.

**Comment by jnarezo** [comment]
Did you use your actual Discord ID? The string of numbers you get by @'ing yourself and putting a backslash "\\" before the tag?

Atelier is designed to ignore every message that doesn't match that ID in the backend to comply with Canvas LMI ToS.

**Comment by Nooboizee** [comment]
Thanks, that was the problem. I was using the bot's ID instead of mine. Thanks for the help!

**Comment by Nooboizee** [comment]
Also, before this is closed, is there a way to get multiple users to be able to use the bot at once?

**Comment by jnarezo** [comment]
In the main directory, in `index.js`, on line 29, removing the check `(msg.author.id != discordUserID)` will allow anyone to interact with it.

Feel free to let me know about any new issues. I actually have been polishing up the bot a lot and fixing things here and there myself, so I'll try to release it before September when I'll be busy.

**Comment by Nooboizee** [comment]
Thank you :)
